(ns kotoba.lang.checkpointer.msgpack-test
  "Hand-rolled msgpack codec, cross-checked against REAL @msgpack/msgpack
  output (test/kotoba/lang/checkpointer/mst_vectors.edn's :msgpack_vectors,
  generated by scripts/gen-mst-vectors.mjs). Byte-identity is checked where
  the two implementations' 'smallest representation' choices coincide
  (which is most of the time); round-trip correctness (decode(encode(x)) ~=
  x, and OUR decode of THEIR bytes) is the actual correctness bar, since
  msgpack here is a wire protocol, not a content-addressing scheme.

  `.clj`, deliberately (not a compliance gap): exercises
  `kotoba.lang.checkpointer.msgpack/encode`/`decode`, which are `:clj`-only-
  wrapped in that (now `.cljc`) namespace, plus JVM `Long/MAX_VALUE`/
  `biginteger` literals and the `.clj` test-vector loader `vectors.clj`."
  (:require [clojure.test :refer [deftest is testing]]
            [kotoba.lang.checkpointer.msgpack :as mp]
            [kotoba.lang.checkpointer.vectors :as v]))

(def clojure-value-for
  "The Clojure-side value each named vector's JS value corresponds to (JS has
  one numeric type, so e.g. the JS `3.0` used for float64 must map to a
  Clojure Double, while the ones used inside `array` are genuine integers --
  see gen-mst-vectors.mjs's comment on this)."
  {"nil" nil
   "true" true
   "false" false
   "zero" 0
   "small_pos_fixint" 42
   "small_neg_fixint" -5
   "uint8" 200
   "uint16" 60000
   "uint32" 3000000000
   "int8" -100
   "int16" -30000
   "int32" -2000000000
   "float64" 3.5
   "str_short" "hi"
   "str_long" (apply str (repeat 500 "x"))
   "bin" (byte-array [1 2 3 255 0])
   "array" [1 "two" 3 nil true]
   "array_with_float" [1 2.5 3]
   "map" {"a" 1 "b" "two" "c" [1 2]}
   "nested" {"op" "put" "meta" {"kind" "writes"} "payload" (byte-array [9 8 7])}})

(deftest byte-identical-vectors
  (doseq [{:keys [name encoded]} (:msgpack_vectors v/vectors)]
    (testing (str "encode(" name ") byte-identical to @msgpack/msgpack")
      (is (contains? clojure-value-for name) (str "no test value mapped for " name))
      (is (= encoded (v/bytes->hex (mp/encode (get clojure-value-for name))))))))

(deftest decode-real-bytes-vectors
  (doseq [{:keys [name encoded]} (:msgpack_vectors v/vectors)]
    (testing (str "decode(@msgpack/msgpack's bytes for " name ") matches the expected Clojure value")
      (let [decoded (mp/decode (v/hex->bytes encoded))
            expected (get clojure-value-for name)]
        (cond
          (bytes? expected) (is (= (vec expected) (vec decoded)))
          (and (map? expected) (some bytes? (vals expected)))
          (is (= (update expected "payload" vec) (update decoded "payload" vec)))
          :else (is (= expected decoded)))))))

(deftest round-trip-test
  (testing "encode then decode returns an equivalent value for representative shapes"
    (doseq [v [nil true false 0 1 -1 127 128 -32 -33 255 256 65535 65536
               4294967295 4294967296 -128 -129 -32768 -32769 -2147483648 -2147483649
               Long/MAX_VALUE Long/MIN_VALUE
               "" "hi" (apply str (repeat 1000 "y"))
               [1 2 3] {} {"a" 1 "b" [1 2 {"c" 3}]}]]
      (is (= v (mp/decode (mp/encode v))) (str "round-trip failed for " (pr-str v))))
    (let [b (byte-array [1 2 3 255 0])]
      (is (= (vec b) (vec (mp/decode (mp/encode b))))))))

(deftest unsigned-64-bit-round-trip-test
  (testing "a uint64 beyond Long/MAX_VALUE round-trips via BigInteger"
    (let [big (biginteger "18446744073709551615")] ; 2^64 - 1
      (is (= big (mp/decode (mp/encode big)))))))
