(ns kotoba.lang.checkpointer.mst-test
  "MST algorithm + CAR determinism, cross-checked against REAL @atproto/repo
  output (test/kotoba/lang/checkpointer/mst_vectors.edn, generated by
  scripts/gen-mst-vectors.mjs from this repo's own installed node_modules --
  never hand-typed). Covers: an empty tree, a single-entry tree (via the
  full commit-mst pipeline, see commit_test.clj), and a deliberately
  multi-layer tree (mst_multi_entry_split, root_layer=2) exercising
  createChild/createParent/splitAround -- not just the trivial single-leaf
  case."
  (:require [clojure.test :refer [deftest is testing]]
            [kotoba.lang.checkpointer.mst :as mst]
            [kotoba.lang.checkpointer.blockmap :as bm]
            [kotoba.lang.checkpointer.car :as car]
            [kotoba.lang.checkpointer.vectors :as v]))

(deftest leading-zeros-on-hash-vectors
  (testing "mst.core/leading-zeros-on-hash (delegated) matches real @atproto/repo's leadingZerosOnHash"
    (doseq [{:keys [key zeros]} (:leading_zeros v/vectors)]
      (is (= zeros (mst/leading-zeros-on-hash key)) (str "key=" (pr-str key))))))

(deftest count-prefix-len-vectors
  (testing "mst.core/common-prefix-len (delegated) matches real @atproto/repo's countPrefixLen"
    (doseq [{:keys [a b n]} (:prefix_len v/vectors)]
      (is (= n (mst/count-prefix-len a b)) (str "a=" (pr-str a) " b=" (pr-str b))))))

(deftest valid-mst-key-test
  (testing "collection/rkey shape, exactly one '/', both halves non-empty + valid chars"
    (is (mst/valid-mst-key? "kotodama.cell.checkpoint/abc-123"))
    (is (not (mst/valid-mst-key? "no-slash")))
    (is (not (mst/valid-mst-key? "a/b/c")))
    (is (not (mst/valid-mst-key? "/b")))
    (is (not (mst/valid-mst-key? "a/")))
    (is (not (mst/valid-mst-key? "a/b#")))
    (testing "1024-char cap (NOT 256 -- see namespace docstring on the kotoba-lang/mst discrepancy)"
      (let [long-rkey (apply str (repeat 1000 "a"))]
        (is (mst/valid-mst-key? (str "coll/" long-rkey)))))))

(deftest empty-tree-test
  (testing "root CID of a brand-new empty MST"
    (is (= (get-in v/vectors [:mst_empty :root])
           (mst/get-pointer (mst/mst-empty))))))

(deftest multi-entry-split-test
  (testing "a deliberately multi-layer tree (root_layer=2) built via repeated mst-add reproduces
            @atproto/repo's exact root CID and CAR bytes"
    (let [{:keys [entries add_order root root_layer car]} (:mst_multi_entry_split v/vectors)
          by-key (into {} (map (fn [e] [(:key e) e])) entries)
          ;; Recompute each value's CID ourselves (double-checks the dag-cbor
          ;; CID pipeline independently of the recorded valueCid) then use
          ;; the recorded valueCid (they must match) as the leaf value.
          blocks (reduce (fn [bm-acc k]
                            (let [[cid bm'] (bm/bm-add bm-acc {"key" k})]
                              (is (= (:valueCid (get by-key k)) cid) (str "value CID mismatch for " k))
                              bm'))
                          (bm/empty-block-map)
                          add_order)
          root-node (reduce (fn [node k] (mst/mst-add node k (:valueCid (get by-key k))))
                             (mst/mst-empty)
                             add_order)]
      (is (= (long root_layer) 2) "sanity: the vector really is multi-layer")
      (is (= root (mst/get-pointer root-node)) "root CID must match byte-for-byte")
      (let [storage-cids (bm/bm-cid-set blocks)
            unstored (mst/get-unstored-blocks root-node storage-cids)
            car-blocks (bm/bm-add-map blocks (:blocks unstored))
            car-bytes (car/blocks->car-bytes (:root unstored) car-blocks)]
        (is (= car (v/bytes->hex car-bytes)) "CAR bytes must match byte-for-byte")))))
